import { useState, useMemo } from "react"
import { Link } from "react-router-dom"
import { useGetProductsQuery, useDeleteProductMutation, useUpdateProductMutation, useCreateProductMutation, useAttachImageMutation } from "@/api/product.api"
import { useGetCategoriesQuery } from "@/api/category.api"
import { useGetCategoryOptionsQuery, useAddProductOptionMutation, useAddProductOptionValueMutation } from "@/api/option.api"
import { Pencil, Trash2, Eye, Plus, X, ChevronDown, ChevronUp } from "lucide-react"
import Button from "@/ui/button/button"
import EmptyState from "@/ui/empty-state/empty-state"
import ImageUpload from "@/ui/image-upload/image-upload"
import { showConfirmModal, showSuccessToast, showErrorModal } from "@/utils/swal"
import type { ProductDto } from "@/api/product.api"
import type { CreateProductDto } from "@/@types/product-api.type"
import type { CategoryOptionDto } from "@/@types/option.type"

// Product option with values for form state
interface ProductOptionConfig {
  categoryOptionId: string
  name: string
  values: string[]
  isExpanded: boolean
}

const initialFormData: CreateProductDto = {
  name: "",
  description: "",
  basePrice: 0,
  compareAtPrice: undefined,
  categoryId: "",
  sku: "",
  barcode: undefined,
  trackInventory: true,
  stockQuantity: 0,
  lowStockThreshold: 5,
  isActive: true,
  metaTitle: undefined,
  metaDescription: undefined,
}

export default function AdminProductsList() {
  const [searchTerm, setSearchTerm] = useState("")
  const [selectedCategory, setSelectedCategory] = useState("")
  const [isCreateModalOpen, setIsCreateModalOpen] = useState(false)
  const [formData, setFormData] = useState<CreateProductDto>({ ...initialFormData })
  const [productImages, setProductImages] = useState<Array<File | string>>([])
  const [productOptions, setProductOptions] = useState<ProductOptionConfig[]>([])

  // API hooks
  const { data: productsData, isLoading: isLoadingProducts, refetch } = useGetProductsQuery({
    search: searchTerm || undefined,
    categoryId: selectedCategory || undefined,
  })
  const { data: categoriesData, isLoading: isLoadingCategories } = useGetCategoriesQuery()
  const { data: categoryOptionsData, isLoading: isLoadingCategoryOptions } = useGetCategoryOptionsQuery(
    formData.categoryId || "",
    { skip: !formData.categoryId || !isCreateModalOpen }
  )
  const [updateProduct, { isLoading: isUpdating }] = useUpdateProductMutation()
  const [deleteProduct, { isLoading: isDeleting }] = useDeleteProductMutation()
  const [createProduct, { isLoading: isCreating }] = useCreateProductMutation()
  const [attachImage] = useAttachImageMutation()
  const [addProductOption] = useAddProductOptionMutation()
  const [addProductOptionValue] = useAddProductOptionValueMutation()

  const products = productsData?.data?.products || []
  const categories = categoriesData?.data?.categories || []
  const categoryOptions = categoryOptionsData?.data || []

  // Initialize product options when category options are loaded
  useMemo(() => {
    if (categoryOptions.length > 0 && productOptions.length === 0) {
      setProductOptions(
        categoryOptions.map((opt: CategoryOptionDto) => ({
          categoryOptionId: opt.id,
          name: opt.name,
          values: [],
          isExpanded: false,
        }))
      )
    }
  }, [categoryOptions, productOptions.length])

  const getCategoryName = (categoryId: string) => {
    const category = categories.find((c) => c.id === categoryId)
    return category?.name || "Uncategorized"
  }

  const handleToggleStatus = async (product: ProductDto) => {
    try {
      const response = await updateProduct({
        id: product.id,
        body: { isActive: !product.isActive }
      }).unwrap()
      if (response.status) {
        showSuccessToast(`Product ${product.isActive ? 'deactivated' : 'activated'} successfully!`)
        refetch()
      } else {
        showErrorModal("Error", response.message || "Failed to update product status")
      }
    } catch (error: any) {
      showErrorModal("Error", error.data?.message || "Failed to update product status")
    }
  }

  const handleDeleteProduct = async (product: ProductDto) => {
    const result = await showConfirmModal(
      "Delete Product",
      `Are you sure you want to delete "${product.name}"? This action cannot be undone.`,
      "Delete",
      "Cancel"
    )

    if (result.isConfirmed) {
      try {
        const response = await deleteProduct(product.id).unwrap()
        if (response.status) {
          showSuccessToast("Product deleted successfully!")
          refetch()
        } else {
          showErrorModal("Error", response.message || "Failed to delete product")
        }
      } catch (error: any) {
        showErrorModal("Error", error.data?.message || "Failed to delete product")
      }
    }
  }

  // Build minimal create payload - backend only accepts these fields on create
  // Note: SKU is auto-generated by the backend
  const buildCreatePayload = () => {
    return {
      name: formData.name,
      description: formData.description,
      categoryId: formData.categoryId,
    }
  }

  // Build update payload - only send fields allowed by backend
  const buildUpdatePayload = () => {
    return {
      name: formData.name,
      description: formData.description,
      compareAtPrice: formData.compareAtPrice,
      categoryId: formData.categoryId,
      barcode: formData.barcode,
      isActive: formData.isActive,
      metaTitle: formData.metaTitle,
      metaDescription: formData.metaDescription,
    }
  }

  // Handle category change - reset options when category changes
  const handleCategoryChange = (categoryId: string) => {
    setFormData({ ...formData, categoryId })
    setProductOptions([])
  }

  // Toggle option expansion
  const toggleOptionExpand = (optionId: string) => {
    setProductOptions(prev =>
      prev.map(opt =>
        opt.categoryOptionId === optionId
          ? { ...opt, isExpanded: !opt.isExpanded }
          : opt
      )
    )
  }

  // Add value to option
  const addOptionValue = (optionId: string, value: string) => {
    if (!value.trim()) return
    setProductOptions(prev =>
      prev.map(opt =>
        opt.categoryOptionId === optionId
          ? { ...opt, values: [...opt.values, value.trim()] }
          : opt
      )
    )
  }

  // Remove value from option
  const removeOptionValue = (optionId: string, valueIndex: number) => {
    setProductOptions(prev =>
      prev.map(opt =>
        opt.categoryOptionId === optionId
          ? { ...opt, values: opt.values.filter((_, i) => i !== valueIndex) }
          : opt
      )
    )
  }

  // Attach options and values to product after creation
  const attachOptionsToProduct = async (productId: string) => {
    const optionsWithValues = productOptions.filter(opt => opt.values.length > 0)

    for (const option of optionsWithValues) {
      try {
        const optionResponse = await addProductOption({
          productId,
          body: { categoryOptionId: option.categoryOptionId }
        }).unwrap()

        if (optionResponse.status && optionResponse.data) {
          const productOptionId = optionResponse.data.id
          for (const value of option.values) {
            await addProductOptionValue({
              productId,
              optionId: productOptionId,
              body: { value }
            }).unwrap()
          }
        }
      } catch (error) {
        console.error("Failed to attach option:", option.name, error)
      }
    }
  }

  // Attach images after product creation (URL only - upload endpoint doesn't exist)
  const attachProductImages = async (productId: string) => {
    for (let index = 0; index < productImages.length; index++) {
      const img = productImages[index]
      try {
        if (typeof img === "string" && img.trim()) {
          // Attach image via URL (JSON)
          await attachImage({
            id: productId,
            body: {
              imageId: img,
              position: index,
              altText: `${formData.name} - Image ${index + 1}`
            }
          }).unwrap()
        }
      } catch (error) {
        console.error("Failed to attach image:", img, error)
      }
    }
  }

  const handleCreateProduct = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      // Step 1: Create product with minimal fields
      const createBody = buildCreatePayload()
      const createResponse = await createProduct(createBody).unwrap()
      
      if (createResponse.status && createResponse.data) {
        const productId = createResponse.data.id
        
        // Step 2: Update product with all other fields
        const updateBody = buildUpdatePayload()
        await updateProduct({ id: productId, body: updateBody }).unwrap()
        
        // Step 3: Attach images if any (URL only)
        if (productImages.length > 0) {
          await attachProductImages(productId)
        }
        
        // Step 4: Attach options to the created product
        await attachOptionsToProduct(productId)
        showSuccessToast("Product created successfully!")
        setIsCreateModalOpen(false)
        setFormData({ ...initialFormData })
        setProductImages([])
        setProductOptions([])
        refetch()
      } else {
        showErrorModal("Error", createResponse.message || "Failed to create product")
      }
    } catch (error: any) {
      console.error("Create product error:", error)
      showErrorModal("Error", error.data?.message || "Failed to create product")
    }
  }

  if (isLoadingProducts || isLoadingCategories) {
    return (
      <div className="bg-white rounded-xl p-6 shadow-sm border border-cdark-100">
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-cblue-600"></div>
        </div>
      </div>
    )
  }

  return (
    <>
      <div className="bg-white rounded-xl p-6 shadow-sm border border-cdark-100">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h4 className="text-xl font-semibold">Products List</h4>
            <p className="text-sm text-cdark-500 mt-1">{products.length} products</p>
          </div>
          <div className="flex gap-3">
            <Button variant="primary" onClick={() => setIsCreateModalOpen(true)}>
              <Plus size={16} className="mr-2" />
              Add Product
            </Button>
          </div>
        </div>

        {/* Filters */}
        <div className="flex gap-4 mb-6">
          <div className="flex-1">
            <input
              type="text"
              placeholder="Search products..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
            />
          </div>
          <div>
            <select
              value={selectedCategory}
              onChange={(e) => setSelectedCategory(e.target.value)}
              className="px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
            >
              <option value="">All Categories</option>
              {categories.map((category) => (
                <option key={category.id} value={category.id}>
                  {category.name}
                </option>
              ))}
            </select>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-cdark-200">
                <th className="text-left py-3 px-2 font-medium text-cdark-500">Image</th>
                <th className="text-left py-3 px-2 font-medium text-cdark-500">Product Name</th>
                <th className="text-left py-3 px-2 font-medium text-cdark-500">Category</th>
                <th className="text-left py-3 px-2 font-medium text-cdark-500">Price</th>
                <th className="text-left py-3 px-2 font-medium text-cdark-500">Stock</th>
                <th className="text-left py-3 px-2 font-medium text-cdark-500">Status</th>
                <th className="text-left py-3 px-2 font-medium text-cdark-500">Actions</th>
              </tr>
            </thead>
            <tbody>
              {products.length === 0 ? (
                <tr>
                  <td colSpan={7} className="py-8">
                    <EmptyState
                      title="No products found"
                      description="Get started by creating your first product"
                    />
                  </td>
                </tr>
              ) : (
                products.map((product) => (
                  <tr key={product.id} className="border-b border-cdark-50 hover:bg-cgrey-50 transition-colors">
                    <td className="py-3 px-2">
                      {product.images?.[0]?.url ? (
                        <img src={product.images[0].url} alt={product.name} className="w-12 h-14 rounded-lg object-cover" />
                      ) : (
                        <div className="w-12 h-14 rounded-lg bg-cgrey-200 flex items-center justify-center text-cdark-400">
                          <i className="ri-image-line" />
                        </div>
                      )}
                    </td>
                    <td className="py-3 px-2 font-medium text-cdark-900">{product.name}</td>
                    <td className="py-3 px-2 text-cdark-600">{getCategoryName(product.categoryId || "")}</td>
                    <td className="py-3 px-2 text-cdark-900 font-medium">${(product.basePrice ?? 0).toFixed(2)}</td>
                    <td className="py-3 px-2 text-cdark-600">{product.stockQuantity ?? 0}</td>
                    <td className="py-3 px-2">
                      <button
                        onClick={() => handleToggleStatus(product)}
                        disabled={isUpdating}
                        className={`px-2 py-1 rounded text-xs font-medium transition-colors ${
                          product.isActive
                            ? "bg-success-50 text-success-700 hover:bg-success-100"
                            : "bg-error-50 text-error-700 hover:bg-error-100"
                        }`}
                      >
                        {product.isActive ? "Active" : "Inactive"}
                      </button>
                    </td>
                    <td className="py-3 px-2">
                      <div className="flex items-center gap-2">
                        <Link
                          to={`/admin/products/${product.id}`}
                          className="p-1.5 hover:bg-cdark-100 rounded-lg text-cdark-500 hover:text-cblue-600 transition-colors"
                          title="View"
                        >
                          <Eye size={16} />
                        </Link>
                        <Link
                          to={`/admin/products/${product.id}/edit`}
                          className="p-1.5 hover:bg-cdark-100 rounded-lg text-cdark-500 hover:text-cblue-600 transition-colors"
                          title="Edit"
                        >
                          <Pencil size={16} />
                        </Link>
                        <button
                          onClick={() => handleDeleteProduct(product)}
                          disabled={isDeleting}
                          className="p-1.5 hover:bg-cdark-100 rounded-lg text-cdark-500 hover:text-error-600 transition-colors"
                          title="Delete"
                        >
                          <Trash2 size={16} />
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Create Product Modal */}
      {isCreateModalOpen && (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
          <div className="bg-white rounded-xl max-w-lg w-full max-h-[90vh] overflow-y-auto">
            <div className="p-6">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h3 className="text-xl font-semibold">Add New Product</h3>
                  <p className="text-sm text-cdark-500 mt-1">Create a new product for your store</p>
                </div>
                <button onClick={() => setIsCreateModalOpen(false)} className="text-cdark-500 hover:text-cdark-700">
                  <X size={20} />
                </button>
              </div>

              <form onSubmit={handleCreateProduct} className="space-y-4">
                <div>
                  <label className="block text-sm font-medium mb-1">Name *</label>
                  <input
                    type="text"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-1">Description</label>
                  <textarea
                    value={formData.description}
                    onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                    rows={3}
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-1">Category *</label>
                  <select
                    value={formData.categoryId}
                    onChange={(e) => handleCategoryChange(e.target.value)}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                    required
                  >
                    <option value="">Select a category</option>
                    {categories.map((category) => (
                      <option key={category.id} value={category.id}>
                        {category.name}
                      </option>
                    ))}
                  </select>
                </div>

                {/* Product Options Section - Shows when category is selected */}
                {formData.categoryId && (
                  <div className="pt-2">
                    <div className="flex items-center justify-between mb-4">
                      <div>
                        <h5 className="text-lg font-medium">Product Options</h5>
                        <p className="text-sm text-cdark-500">
                          Configure options for this product
                        </p>
                      </div>
                      {isLoadingCategoryOptions && (
                        <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-cblue-600"></div>
                      )}
                    </div>

                    {categoryOptions.length === 0 && !isLoadingCategoryOptions && (
                      <p className="text-sm text-cdark-500 italic">
                        No options available for this category.
                      </p>
                    )}

                    <div className="space-y-3">
                      {productOptions.map((option) => (
                        <div key={option.categoryOptionId} className="border border-cdark-200 rounded-lg">
                          <button
                            type="button"
                            onClick={() => toggleOptionExpand(option.categoryOptionId)}
                            className="w-full flex items-center justify-between p-3 hover:bg-cgrey-50 rounded-lg transition-colors"
                          >
                            <div className="flex items-center gap-2">
                              <span className="font-medium">{option.name}</span>
                              {option.values.length > 0 && (
                                <span className="text-xs bg-cblue-100 text-cblue-700 px-2 py-0.5 rounded-full">
                                  {option.values.length}
                                </span>
                              )}
                            </div>
                            {option.isExpanded ? (
                              <ChevronUp size={18} className="text-cdark-500" />
                            ) : (
                              <ChevronDown size={18} className="text-cdark-500" />
                            )}
                          </button>

                          {option.isExpanded && (
                            <div className="p-3 pt-0 border-t border-cdark-100">
                              <div className="flex flex-wrap gap-2 mt-3">
                                {option.values.map((value, index) => (
                                  <div
                                    key={index}
                                    className="flex items-center gap-1 px-2 py-1 bg-cblue-50 text-cblue-700 rounded-md text-sm"
                                  >
                                    <span>{value}</span>
                                    <button
                                      type="button"
                                      onClick={() => removeOptionValue(option.categoryOptionId, index)}
                                      className="hover:text-error-600"
                                    >
                                      <X size={14} />
                                    </button>
                                  </div>
                                ))}
                              </div>

                              <div className="flex gap-2 mt-3">
                                <input
                                  type="text"
                                  placeholder={`Add ${option.name} value...`}
                                  className="flex-1 px-3 py-2 text-sm rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                                  onKeyDown={(e) => {
                                    if (e.key === "Enter") {
                                      e.preventDefault()
                                      addOptionValue(option.categoryOptionId, e.currentTarget.value)
                                      e.currentTarget.value = ""
                                    }
                                  }}
                                />
                                <Button
                                  type="button"
                                  variant="secondary"
                                  onClick={(e) => {
                                    const input = (e.currentTarget.previousSibling as HTMLInputElement)
                                    addOptionValue(option.categoryOptionId, input.value)
                                    input.value = ""
                                  }}
                                >
                                  <Plus size={16} />
                                </Button>
                              </div>
                            </div>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                )}

                <div>
                  <label className="block text-sm font-medium mb-1">Base Price *</label>
                  <input
                    type="number"
                    step="0.01"
                    value={formData.basePrice}
                    onChange={(e) => setFormData({ ...formData, basePrice: parseFloat(e.target.value) || 0 })}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                    required
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-1">Compare at Price</label>
                  <input
                    type="number"
                    step="0.01"
                    value={formData.compareAtPrice ?? ""}
                    onChange={(e) => setFormData({ ...formData, compareAtPrice: parseFloat(e.target.value) || undefined })}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-1">Stock Quantity *</label>
                  <input
                    type="number"
                    value={formData.stockQuantity}
                    onChange={(e) => setFormData({ ...formData, stockQuantity: parseInt(e.target.value) || 0 })}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                    required
                  />
                </div>

                <div>
                  <div className="flex items-center justify-between mb-2">
                    <label className="block text-sm font-medium">Images</label>
                    <span className="text-xs text-cdark-500">{productImages.length} added</span>
                  </div>
                  <div className="space-y-2">
                    {productImages.map((img, index) => (
                      <div key={index} className="flex items-center gap-2 p-2 bg-cgrey-50 rounded-lg">
                        <div className="flex-1">
                          <ImageUpload
                            value={img}
                            onChange={(newValue) => {
                              const newImages = [...productImages]
                              newImages[index] = newValue || ""
                              setProductImages(newImages)
                            }}
                          />
                        </div>
                        <button
                          type="button"
                          onClick={() => setProductImages(productImages.filter((_, i) => i !== index))}
                          className="p-1.5 text-cdark-500 hover:text-error-600"
                        >
                          <X size={16} />
                        </button>
                      </div>
                    ))}
                    <Button
                      type="button"
                      variant="secondary"
                      onClick={() => setProductImages([...productImages, ""])}
                      className="w-full"
                    >
                      <Plus size={16} className="mr-2" />
                      Add Image
                    </Button>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="isActive"
                      checked={formData.isActive}
                      onChange={(e) => setFormData({ ...formData, isActive: e.target.checked })}
                      className="rounded border-cdark-300 text-cblue-600 focus:ring-cblue-500"
                    />
                    <label htmlFor="isActive" className="text-sm font-medium">Active</label>
                  </div>

                  <div className="flex items-center gap-2">
                    <input
                      type="checkbox"
                      id="trackInventory"
                      checked={formData.trackInventory}
                      onChange={(e) => setFormData({ ...formData, trackInventory: e.target.checked })}
                      className="rounded border-cdark-300 text-cblue-600 focus:ring-cblue-500"
                    />
                    <label htmlFor="trackInventory" className="text-sm font-medium">Track Inventory</label>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium mb-1">Low Stock Threshold</label>
                  <input
                    type="number"
                    value={formData.lowStockThreshold ?? 5}
                    onChange={(e) => setFormData({ ...formData, lowStockThreshold: parseInt(e.target.value) || 5 })}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium mb-1">Barcode</label>
                  <input
                    type="text"
                    value={formData.barcode ?? ""}
                    onChange={(e) => setFormData({ ...formData, barcode: e.target.value || undefined })}
                    className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                  />
                </div>

                {/* SEO Section */}
                <div className="pt-2">
                  <h5 className="text-lg font-medium mb-4">SEO Settings</h5>
                  <div className="space-y-4">
                    <div>
                      <label className="block text-sm font-medium mb-1">Meta Title</label>
                      <input
                        type="text"
                        value={formData.metaTitle ?? ""}
                        onChange={(e) => setFormData({ ...formData, metaTitle: e.target.value || undefined })}
                        className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                      />
                    </div>

                    <div>
                      <label className="block text-sm font-medium mb-1">Meta Description</label>
                      <input
                        type="text"
                        value={formData.metaDescription ?? ""}
                        onChange={(e) => setFormData({ ...formData, metaDescription: e.target.value || undefined })}
                        className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                      />
                    </div>
                  </div>
                </div>

                {/* Actions */}
                <div className="flex justify-end gap-3 pt-6 border-t">
                  <Button variant="secondary" type="button" onClick={() => setIsCreateModalOpen(false)}>
                    Cancel
                  </Button>
                  <Button variant="primary" type="submit" disabled={isCreating}>
                    {isCreating ? "Creating..." : "Create Product"}
                  </Button>
                </div>
              </form>
            </div>
          </div>
        </div>
      )}
    </>
  )
}
