import { useState, useMemo } from "react"
import { Link, useNavigate } from "react-router-dom"
import { useCreateProductMutation, useUpdateProductMutation, useAttachImageMutation } from "@/api/product.api"
import { useGetCategoriesQuery } from "@/api/category.api"
import { useGetCategoryOptionsQuery, useAddProductOptionMutation, useAddProductOptionValueMutation } from "@/api/option.api"
import { X, Plus, ArrowLeft, ChevronDown, ChevronUp } from "lucide-react"
import Button from "@/ui/button/button"
import ImageUpload from "@/ui/image-upload/image-upload"
import { showSuccessToast, showErrorModal } from "@/utils/swal"
import type { CreateProductDto } from "@/@types/product-api.type"
import type { CategoryOptionDto } from "@/@types/option.type"

// Product option with values for form state
interface ProductOptionConfig {
  categoryOptionId: string
  name: string
  values: string[]
  isExpanded: boolean
}

export default function AdminProductsCreate() {
  const navigate = useNavigate()
  const [formData, setFormData] = useState<CreateProductDto>({
    name: "",
    description: "",
    basePrice: 0,
    compareAtPrice: undefined,
    categoryId: "",
    sku: "",
    barcode: undefined,
    trackInventory: true,
    stockQuantity: 0,
    lowStockThreshold: 5,
    isActive: true,
    metaTitle: undefined,
    metaDescription: undefined,
  })
  const [productImages, setProductImages] = useState<Array<File | string>>([])
  const [productOptions, setProductOptions] = useState<ProductOptionConfig[]>([])

  // API hooks
  const { data: categoriesData, isLoading: isLoadingCategories } = useGetCategoriesQuery()
  const { data: categoryOptionsData, isLoading: isLoadingCategoryOptions } = useGetCategoryOptionsQuery(
    formData.categoryId || "",
    { skip: !formData.categoryId }
  )
  const [createProduct, { isLoading: isCreating }] = useCreateProductMutation()
  const [updateProduct] = useUpdateProductMutation()
  const [attachImage] = useAttachImageMutation()
  const [addProductOption] = useAddProductOptionMutation()
  const [addProductOptionValue] = useAddProductOptionValueMutation()

  const categories = categoriesData?.data?.categories || []
  const categoryOptions = categoryOptionsData?.data || []

  // Initialize product options when category options are loaded
  useMemo(() => {
    if (categoryOptions.length > 0 && productOptions.length === 0) {
      setProductOptions(
        categoryOptions.map((opt: CategoryOptionDto) => ({
          categoryOptionId: opt.id,
          name: opt.name,
          values: [],
          isExpanded: false,
        }))
      )
    }
  }, [categoryOptions, productOptions.length])

  // Build minimal create payload - backend only accepts these fields on create
  // Note: SKU is auto-generated by the backend
  const buildCreatePayload = () => {
    return {
      name: formData.name,
      description: formData.description,
      categoryId: formData.categoryId,
    }
  }

  // Build update payload - only send fields allowed by backend
  const buildUpdatePayload = () => {
    return {
      name: formData.name,
      description: formData.description,
      compareAtPrice: formData.compareAtPrice,
      categoryId: formData.categoryId,
      barcode: formData.barcode,
      isActive: formData.isActive,
      metaTitle: formData.metaTitle,
      metaDescription: formData.metaDescription,
    }
  }

  // Handle category change - reset options when category changes
  const handleCategoryChange = (categoryId: string) => {
    setFormData({ ...formData, categoryId })
    setProductOptions([])
  }

  // Toggle option expansion
  const toggleOptionExpand = (optionId: string) => {
    setProductOptions(prev =>
      prev.map(opt =>
        opt.categoryOptionId === optionId
          ? { ...opt, isExpanded: !opt.isExpanded }
          : opt
      )
    )
  }

  // Add value to option
  const addOptionValue = (optionId: string, value: string) => {
    if (!value.trim()) return
    setProductOptions(prev =>
      prev.map(opt =>
        opt.categoryOptionId === optionId
          ? { ...opt, values: [...opt.values, value.trim()] }
          : opt
      )
    )
  }

  // Remove value from option
  const removeOptionValue = (optionId: string, valueIndex: number) => {
    setProductOptions(prev =>
      prev.map(opt =>
        opt.categoryOptionId === optionId
          ? { ...opt, values: opt.values.filter((_, i) => i !== valueIndex) }
          : opt
      )
    )
  }

  // Attach options and values to product after creation
  const attachOptionsToProduct = async (productId: string) => {
    const optionsWithValues = productOptions.filter(opt => opt.values.length > 0)

    for (const option of optionsWithValues) {
      try {
        // Add the option to product
        const optionResponse = await addProductOption({
          productId,
          body: { categoryOptionId: option.categoryOptionId }
        }).unwrap()

        if (optionResponse.status && optionResponse.data) {
          const productOptionId = optionResponse.data.id

          // Add values to the option
          for (const value of option.values) {
            await addProductOptionValue({
              productId,
              optionId: productOptionId,
              body: { value }
            }).unwrap()
          }
        }
      } catch (error) {
        console.error("Failed to attach option:", option.name, error)
      }
    }
  }

  // Attach images after product creation (URL only - upload endpoint doesn't exist)
  const attachProductImages = async (productId: string) => {
    for (let index = 0; index < productImages.length; index++) {
      const img = productImages[index]
      try {
        if (typeof img === "string" && img.trim()) {
          // Attach image via URL (JSON)
          await attachImage({
            id: productId,
            body: {
              imageId: img,
              position: index,
              altText: `${formData.name} - Image ${index + 1}`
            }
          }).unwrap()
        }
      } catch (error) {
        console.error("Failed to attach image:", img, error)
      }
    }
  }

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    try {
      // Step 1: Create product with minimal fields
      const createBody = buildCreatePayload()
      const createResponse = await createProduct(createBody).unwrap()
      
      if (createResponse.status && createResponse.data) {
        const productId = createResponse.data.id
        
        // Step 2: Update product with all other fields
        const updateBody = buildUpdatePayload()
        await updateProduct({ id: productId, body: updateBody }).unwrap()
        
        // Step 3: Attach images if any (URL only)
        if (productImages.length > 0) {
          await attachProductImages(productId)
        }
        
        // Step 4: Attach options to the created product
        await attachOptionsToProduct(productId)
        showSuccessToast("Product created successfully!")
        navigate("/admin/products")
      } else {
        showErrorModal("Error", createResponse.message || "Failed to create product")
      }
    } catch (error: any) {
      console.error("Create product error:", error)
      showErrorModal("Error", error.data?.message || "Failed to create product")
    }
  }

  if (isLoadingCategories) {
    return (
      <div className="bg-white rounded-xl p-6 shadow-sm border border-cdark-100">
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-cblue-600"></div>
        </div>
      </div>
    )
  }

  return (
    <div className="bg-white rounded-xl p-6 shadow-sm border border-cdark-100">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-4">
          <Link
            to="/admin/products"
            className="p-2 hover:bg-cgrey-100 rounded-lg text-cdark-500 hover:text-cdark-700 transition-colors"
          >
            <ArrowLeft size={20} />
          </Link>
          <div>
            <h4 className="text-xl font-semibold">Add New Product</h4>
            <p className="text-sm text-cdark-500 mt-1">Create a new product for your store</p>
          </div>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="space-y-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {/* Basic Information */}
          <div className="space-y-4">
            <div>
              <label className="block text-sm font-medium mb-1">Name *</label>
              <input
                type="text"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                required
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Description</label>
              <textarea
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                rows={4}
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Category *</label>
              <select
                value={formData.categoryId}
                onChange={(e) => handleCategoryChange(e.target.value)}
                className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                required
              >
                <option value="">Select a category</option>
                {categories.map((category) => (
                  <option key={category.id} value={category.id}>
                    {category.name}
                  </option>
                ))}
              </select>
            </div>

            {/* Product Options Section - Shows when category is selected */}
            {formData.categoryId && (
              <div className="pt-2">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <h5 className="text-lg font-medium">Product Options</h5>
                    <p className="text-sm text-cdark-500">
                      Configure options for this product based on category
                    </p>
                  </div>
                  {isLoadingCategoryOptions && (
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-cblue-600"></div>
                  )}
                </div>

                {categoryOptions.length === 0 && !isLoadingCategoryOptions && (
                  <p className="text-sm text-cdark-500 italic">
                    No options available for this category. Add options in the Options page.
                  </p>
                )}

                <div className="space-y-3">
                  {productOptions.map((option) => (
                    <div key={option.categoryOptionId} className="border border-cdark-200 rounded-lg">
                      {/* Option Header */}
                      <button
                        type="button"
                        onClick={() => toggleOptionExpand(option.categoryOptionId)}
                        className="w-full flex items-center justify-between p-3 hover:bg-cgrey-50 rounded-lg transition-colors"
                      >
                        <div className="flex items-center gap-2">
                          <span className="font-medium">{option.name}</span>
                          {option.values.length > 0 && (
                            <span className="text-xs bg-cblue-100 text-cblue-700 px-2 py-0.5 rounded-full">
                              {option.values.length} values
                            </span>
                          )}
                        </div>
                        {option.isExpanded ? (
                          <ChevronUp size={18} className="text-cdark-500" />
                        ) : (
                          <ChevronDown size={18} className="text-cdark-500" />
                        )}
                      </button>

                      {/* Option Values */}
                      {option.isExpanded && (
                        <div className="p-3 pt-0 border-t border-cdark-100">
                          {/* Values List */}
                          <div className="flex flex-wrap gap-2 mt-3">
                            {option.values.map((value, index) => (
                              <div
                                key={index}
                                className="flex items-center gap-1 px-2 py-1 bg-cblue-50 text-cblue-700 rounded-md text-sm"
                              >
                                <span>{value}</span>
                                <button
                                  type="button"
                                  onClick={() => removeOptionValue(option.categoryOptionId, index)}
                                  className="hover:text-error-600"
                                >
                                  <X size={14} />
                                </button>
                              </div>
                            ))}
                          </div>

                          {/* Add Value Input */}
                          <div className="flex gap-2 mt-3">
                            <input
                              type="text"
                              placeholder={`Add ${option.name} value...`}
                              className="flex-1 px-3 py-2 text-sm rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                              onKeyDown={(e) => {
                                if (e.key === "Enter") {
                                  e.preventDefault()
                                  addOptionValue(option.categoryOptionId, e.currentTarget.value)
                                  e.currentTarget.value = ""
                                }
                              }}
                            />
                            <Button
                              type="button"
                              variant="secondary"
                              onClick={(e) => {
                                const input = (e.currentTarget.previousSibling as HTMLInputElement)
                                addOptionValue(option.categoryOptionId, input.value)
                                input.value = ""
                              }}
                            >
                              <Plus size={16} />
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Base Price *</label>
                <input
                  type="number"
                  step="0.01"
                  value={formData.basePrice}
                  onChange={(e) => setFormData({ ...formData, basePrice: parseFloat(e.target.value) || 0 })}
                  className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                  required
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Compare at Price</label>
                <input
                  type="number"
                  step="0.01"
                  value={formData.compareAtPrice ?? ""}
                  onChange={(e) => setFormData({ ...formData, compareAtPrice: parseFloat(e.target.value) || undefined })}
                  className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                />
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-medium mb-1">Barcode</label>
                <input
                  type="text"
                  value={formData.barcode ?? ""}
                  onChange={(e) => setFormData({ ...formData, barcode: e.target.value || undefined })}
                  className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                />
              </div>

              <div>
                <label className="block text-sm font-medium mb-1">Stock Quantity *</label>
                <input
                  type="number"
                  value={formData.stockQuantity}
                  onChange={(e) => setFormData({ ...formData, stockQuantity: parseInt(e.target.value) || 0 })}
                  className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
                  required
                />
              </div>
            </div>
          </div>

          {/* Images and Settings */}
          <div className="space-y-4">
            {/* Images Section */}
            <div>
              <div className="flex items-center justify-between mb-2">
                <label className="block text-sm font-medium">Images</label>
                <span className="text-xs text-cdark-500">{productImages.length} added</span>
              </div>
              <div className="space-y-2">
                {productImages.map((img, index) => (
                  <div key={index} className="flex items-center gap-2 p-2 bg-cgrey-50 rounded-lg">
                    <div className="flex-1">
                      <ImageUpload
                        value={img}
                        onChange={(newValue) => {
                          const newImages = [...productImages]
                          newImages[index] = newValue || ""
                          setProductImages(newImages)
                        }}
                      />
                    </div>
                    <button
                      type="button"
                      onClick={() => setProductImages(productImages.filter((_, i) => i !== index))}
                      className="p-1.5 text-cdark-500 hover:text-error-600"
                    >
                      <X size={16} />
                    </button>
                  </div>
                ))}
                <Button
                  type="button"
                  variant="secondary"
                  onClick={() => setProductImages([...productImages, ""])}
                  className="w-full"
                >
                  <Plus size={16} className="mr-2" />
                  Add Image
                </Button>
              </div>
            </div>

            {/* Settings */}
            <div className="space-y-3">
              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="isActive"
                  checked={formData.isActive}
                  onChange={(e) => setFormData({ ...formData, isActive: e.target.checked })}
                  className="rounded border-cdark-300 text-cblue-600 focus:ring-cblue-500"
                />
                <label htmlFor="isActive" className="text-sm font-medium">Active</label>
              </div>

              <div className="flex items-center gap-2">
                <input
                  type="checkbox"
                  id="trackInventory"
                  checked={formData.trackInventory}
                  onChange={(e) => setFormData({ ...formData, trackInventory: e.target.checked })}
                  className="rounded border-cdark-300 text-cblue-600 focus:ring-cblue-500"
                />
                <label htmlFor="trackInventory" className="text-sm font-medium">Track Inventory</label>
              </div>
            </div>

            {/* Additional Fields */}
            <div>
              <label className="block text-sm font-medium mb-1">Low Stock Threshold</label>
              <input
                type="number"
                value={formData.lowStockThreshold ?? 5}
                onChange={(e) => setFormData({ ...formData, lowStockThreshold: parseInt(e.target.value) || 5 })}
                className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
              />
            </div>
          </div>
        </div>

        {/* SEO Section */}
        <div className="pt-2">
          <h5 className="text-lg font-medium mb-4">SEO Settings</h5>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-medium mb-1">Meta Title</label>
              <input
                type="text"
                value={formData.metaTitle ?? ""}
                onChange={(e) => setFormData({ ...formData, metaTitle: e.target.value || undefined })}
                className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
              />
            </div>

            <div>
              <label className="block text-sm font-medium mb-1">Meta Description</label>
              <input
                type="text"
                value={formData.metaDescription ?? ""}
                onChange={(e) => setFormData({ ...formData, metaDescription: e.target.value || undefined })}
                className="w-full px-4 py-2 rounded-lg border border-cdark-200 focus:outline-none focus:border-cblue-500"
              />
            </div>
          </div>
        </div>

        {/* Actions */}
        <div className="flex justify-end gap-3 pt-6">
          <Link to="/admin/products">
            <Button variant="secondary" type="button">
              Cancel
            </Button>
          </Link>
          <Button variant="primary" type="submit" disabled={isCreating}>
            {isCreating ? "Creating..." : "Create Product"}
          </Button>
        </div>
      </form>
    </div>
  )
}