import type { Product } from "@/@types/product.type"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Turtleneck T-shirt",
    slug: "turtleneck-t-shirt",
    price: 100,
    compareAtPrice: 130,
    images: ["/images/products/fashion/product-3.jpg", "/images/products/fashion/product-4.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "Yellow", value: "#fde047", image: "/images/products/fashion/product-3.jpg" },
      { name: "Grey", value: "#9ca3af", image: "/images/products/fashion/product-6.jpg" },
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-4.jpg" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    badge: "sale",
    description: "Pants in an airy weave made from a linen and viscose blend.",
    inStock: true,
    rating: 4.5,
    reviewCount: 128,
  },
  {
    id: "2",
    name: "Loose Fit Tee",
    slug: "loose-fit-tee",
    price: 120,
    images: ["/images/products/fashion/product-29.jpg", "/images/products/fashion/product-20.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "Purple", value: "#c084fc", image: "/images/products/fashion/product-8.jpg" },
      { name: "Grey", value: "#9ca3af", image: "/images/products/fashion/product-7.jpg" },
      { name: "Light Orange", value: "#fdba74", image: "/images/products/fashion/product-28.jpg" },
    ],
    badge: "trending",
    description: "A relaxed-fit tee for everyday comfort.",
    inStock: true,
    rating: 4.2,
    reviewCount: 95,
  },
  {
    id: "3",
    name: "Crop T-shirt",
    slug: "crop-t-shirt",
    price: 120,
    compareAtPrice: 140,
    images: ["/images/products/fashion/product-1.jpg", "/images/products/fashion/product-5.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-1.jpg" },
      { name: "Grey", value: "#9ca3af", image: "/images/products/fashion/product-5.jpg" },
      { name: "Black", value: "#1c1917", image: "/images/products/fashion/product-22.jpg" },
    ],
    sizes: ["S", "M", "L", "XL"],
    badge: "sale",
    description: "A stylish crop tee with a modern silhouette.",
    inStock: true,
    rating: 4.7,
    reviewCount: 210,
  },
  {
    id: "4",
    name: "Short Sleeve Sweat",
    slug: "short-sleeve-sweat",
    price: 80,
    compareAtPrice: 100,
    images: ["/images/products/fashion/product-4.jpg", "/images/products/fashion/product-23.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-4.jpg" },
      { name: "Purple", value: "#a78bfa", image: "/images/products/fashion/product-23.jpg" },
    ],
    badge: "sale",
    description: "Lightweight sweat for transitional weather.",
    inStock: true,
    rating: 4.0,
    reviewCount: 64,
  },
  {
    id: "5",
    name: "Puff Sleeve Shirred Blouse",
    slug: "puff-sleeve-shirred-blouse",
    price: 80,
    images: ["/images/products/fashion/women-yellow-2.jpg", "/images/products/fashion/product-28.jpg"],
    category: "Women",
    categorySlug: "women",
    colors: [
      { name: "Yellow", value: "#fbbf24", image: "/images/products/fashion/women-yellow-2.jpg" },
      { name: "Light Orange", value: "#fdba74", image: "/images/products/fashion/product-28.jpg" },
      { name: "Beige", value: "#d4b896", image: "/images/products/fashion/product-7.jpg" },
    ],
    description: "Elegant puff sleeve blouse with shirred detailing.",
    inStock: true,
    rating: 4.3,
    reviewCount: 77,
  },
  {
    id: "6",
    name: "Printed T-shirt",
    slug: "printed-t-shirt",
    price: 120,
    images: ["/images/products/fashion/product-26.jpg", "/images/products/fashion/product-26.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-26.jpg" },
      { name: "Grey", value: "#9ca3af", image: "/images/products/fashion/women-grey-1.jpg" },
      { name: "Black", value: "#1c1917", image: "/images/products/fashion/women-black-6.jpg" },
    ],
    sizes: ["S", "M", "L"],
    description: "Graphic printed tee for casual days.",
    inStock: true,
    rating: 4.1,
    reviewCount: 43,
  },
  {
    id: "7",
    name: "Polo Neck T-Shirt",
    slug: "polo-neck-t-shirt",
    price: 100,
    compareAtPrice: 130,
    images: ["/images/products/fashion/product-29.jpg", "/images/products/fashion/product-6.jpg"],
    category: "Men",
    categorySlug: "men",
    colors: [
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-29.jpg" },
      { name: "Grey", value: "#9ca3af", image: "/images/products/fashion/product-6.jpg" },
      { name: "Black", value: "#1c1917", image: "/images/products/fashion/product-20.jpg" },
    ],
    sizes: ["XS", "S", "M", "L", "XL", "2XL"],
    badge: "sale",
    description: "Classic polo neck for a refined look.",
    inStock: true,
    rating: 4.6,
    reviewCount: 182,
  },
  {
    id: "8",
    name: "Oversized Fit Tee",
    slug: "oversized-fit-tee",
    price: 60,
    compareAtPrice: 80,
    images: ["/images/products/fashion/product-6.jpg", "/images/products/fashion/product-21.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-6.jpg" },
      { name: "Dark Green", value: "#166534", image: "/images/products/fashion/product-21.jpg" },
    ],
    badge: "sale",
    description: "Oversized comfort fit tee.",
    inStock: true,
    rating: 3.9,
    reviewCount: 31,
  },
  {
    id: "9",
    name: "Daystak Chair RD1",
    slug: "daystak-chair-rd1",
    price: 100,
    compareAtPrice: 130,
    images: ["/images/products/fashion/product-12.jpg", "/images/products/fashion/product-20.jpg"],
    category: "Accessories",
    categorySlug: "accessories",
    colors: [
      { name: "Yellow", value: "#fdba74", image: "/images/products/fashion/product-12.jpg" },
      { name: "Grey", value: "#9ca3af", image: "/images/products/fashion/product-6.jpg" },
      { name: "Black", value: "#1c1917", image: "/images/products/fashion/product-20.jpg" },
    ],
    badge: "sale",
    description: "Modern chair with sleek design.",
    inStock: true,
    rating: 4.8,
    reviewCount: 256,
  },
  {
    id: "10",
    name: "Striped T-Shirt",
    slug: "striped-t-shirt",
    price: 100,
    compareAtPrice: 130,
    images: ["/images/products/fashion/product-40.jpg", "/images/products/fashion/product-41.jpg", "/images/products/fashion/product-42.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "Orange", value: "#fdba74", image: "/images/products/fashion/product-40.jpg" },
      { name: "Green", value: "#86efac", image: "/images/products/fashion/product-41.jpg" },
      { name: "Pink", value: "#f9a8d4", image: "/images/products/fashion/product-42.jpg" },
    ],
    sizes: ["S", "M", "L", "XL"],
    badge: "sale",
    description: "Striped tee with bold colorways.",
    inStock: true,
    rating: 4.4,
    reviewCount: 99,
  },
  {
    id: "11",
    name: "Polo T-Shirt",
    slug: "polo-t-shirt",
    price: 130,
    compareAtPrice: 150,
    images: ["/images/products/fashion/product-1.jpg", "/images/products/fashion/product-2.jpg"],
    category: "Men",
    categorySlug: "men",
    colors: [
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-1.jpg" },
    ],
    description: "Premium polo tee with classic collar.",
    inStock: true,
    rating: 4.5,
    reviewCount: 112,
  },
  {
    id: "12",
    name: "Short Sleeve Sweat 2",
    slug: "short-sleeve-sweat-2",
    price: 100,
    compareAtPrice: 115,
    images: ["/images/products/fashion/product-2.jpg", "/images/products/fashion/product-2.jpg"],
    category: "Tops",
    categorySlug: "tops",
    colors: [
      { name: "White", value: "#ffffff", image: "/images/products/fashion/product-2.jpg" },
    ],
    description: "Casual short sleeve sweat.",
    inStock: true,
    rating: 4.0,
    reviewCount: 55,
  },
]
